from selenium.webdriver.common.by import By

class OrderPageLocators:
    FIRST_NAME_INPUT = (By.XPATH, "//input[@placeholder='* Имя']")
    SECOND_NAME_INPUT = (By.XPATH, "//input[@placeholder='* Фамилия']")
    ADRESS_INPUT = (By.XPATH, "//input[@placeholder='* Адрес: куда привезти заказ']")
    PHONE_INPUT = (By.XPATH, "//input[@placeholder='* Телефон: на него позвонит курьер']")
    METRO_BUTTON = (By.XPATH, "//input[@placeholder='* Станция метро']")
    METRO_ITEM = (By.XPATH, "//button[@class='Order_SelectOption__82bhS select-search__option']")
    NEXT_BUTTON = (By.CLASS_NAME, "Button_Middle__1CSJM")
    DATE_INPUT = (By.XPATH, "//input[@placeholder='* Когда привезти самокат']")
    DATEPICKER = (By.CLASS_NAME, "react-datepicker")
    DATEPICKER_DAY = (By.CLASS_NAME, "react-datepicker__day")
    RENTAL_PERIOD_BUTTON = (By.CLASS_NAME, "Dropdown-control")
    RENTAL_DROPDOWN_MENU = (By.CLASS_NAME, "Dropdown-menu")
    RENTAL_PERIOD_OPTION = (By.XPATH, "//div[@class='Dropdown-root is-open']//div[@class='Dropdown-option']")
    COLOR_SCOOTER_CHECKBOX = (By.CLASS_NAME, 'Checkbox_Input__14A2w')
    COMMENT_INPUT = (By.XPATH, "//input[@placeholder='Комментарий для курьера']")
    ORDER_BUTTON = (By.XPATH, "//div[@class='Order_Buttons__1xGrp']//button[text()='Заказать']")
    ORDER_MODAL = (By.CLASS_NAME, "Order_Modal__YZ-d3")
    ORDER_CONFIRMATION_BUTTON = (By.XPATH, "//button[text()='Да']")
    ORDER_MODAL_HEADER = (By.CLASS_NAME, "Order_ModalHeader__3FDaJ")
    CHECK_STATUS_BUTTON = (By.XPATH, "//button[text()='Посмотреть статус']")
    LOGO_SCOOTER = (By.XPATH, "//img[@alt='Scooter']")
    LOGO_YANDEX = (By.XPATH, "//img[@alt='Yandex']")